import groovy.lang.Closure
import io.papermc.paperweight.userdev.ReobfArtifactConfiguration
import net.minecrell.pluginyml.bukkit.BukkitPluginDescription
import net.minecrell.pluginyml.paper.PaperPluginDescription

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.14"
    id("xyz.jpenilla.run-paper") version "2.3.1" // Adds runServer and runMojangMappedServer tasks for testing
    id("net.minecrell.plugin-yml.paper") version "0.6.0" // Generates plugin.yml
    id("io.github.goooler.shadow") version "8.1.7" // Shadow PluginBase
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.md-5.net/content/groups/public/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.playpro.com")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }

    maven {
        name = "glaremasters repo"
        url = uri("https://repo.glaremasters.me/repository/towny/")
    }
}

paperweight.reobfArtifactConfiguration = ReobfArtifactConfiguration.MOJANG_PRODUCTION

dependencies {
    paperweight.paperDevBundle("${project.property("minecraft_version")}")

    //compileOnly("com.comphenix.protocol:ProtocolLib:${project.property("protocollib_version")}")

    //compileOnly(files("libs/CMILib1.4.3.5.jar"))
    //compileOnly(files("libs/Residence5.1.4.0.jar"))

    compileOnly("com.github.retrooper:packetevents-spigot:${project.property("packetevents_version")}")

    compileOnly("com.palmergames.bukkit.towny:towny:${project.property("towny_version")}")

    implementation("org.bstats:bstats-bukkit:${project.property("bstats_version")}")
    {
        exclude("com.google.code.gson", "gson")
    }

    //implementation("org.apache.httpcomponents.client5:httpclient5:5.2.1")

    var pbVersion = if (project.property("pluginbase_use_local")!!.equals("true"))
                        project.property("pluginbase_local")
                    else
                        project.property("pluginbase_version");

    System.out.println("[PluginBase] Will use PluginBase version ${pbVersion}")

    implementation("com.github.XiaMoZhiShi:PluginBase:${pbVersion}")
    {
        exclude("com.google.code.gson", "gson")
    }

    //compileOnly("com.github.Gecolay:GSit:${project.property("gsit_version")}")
    compileOnly("me.clip:placeholderapi:${project.property("papi_version")}")
    compileOnly("net.coreprotect:coreprotect:22.2")
}

group = "xyz.nifeather.fexp"
version = "${project.property("project_version")}"
description = "Feather Experience!"
java.sourceCompatibility = JavaVersion.VERSION_21

paper {
    load = BukkitPluginDescription.PluginLoadOrder.POSTWORLD
    main = "xyz.nifeather.fexp.FeatherExperience"
    bootstrapper = "xyz.nifeather.fexp.FeatherExperienceBootstrap"
    apiVersion = "1.21"
    authors = listOf("MATRIX-feather")
    version = "${project.property("project_version")}"
    prefix = "FeatherExperience"
    name = "FeatherExperience"
    foliaSupported = true

    serverDependencies {
        register("packetevents") {
            load = PaperPluginDescription.RelativeLoadOrder.BEFORE;
            required = false;
            joinClasspath = true
        }
        register("CoreProtect") {
            load = PaperPluginDescription.RelativeLoadOrder.BEFORE;
            required = false;
            joinClasspath = true
        }
        register("Towny") {
            load = PaperPluginDescription.RelativeLoadOrder.BEFORE;
            required = false;
            joinClasspath = true
        }
        register("PlaceholderAPI") {
            load = PaperPluginDescription.RelativeLoadOrder.BEFORE;
            required = false;
            joinClasspath = true
        }
    }
/*
    commands {
        var mainCommand = register("fexp").get();

        mainCommand.aliases = listOf("fe");

        register("fpvp")
    }
*/
    val permissionRoot = "fexp"

    permissions {
        register("${permissionRoot}.cmd").get().default = BukkitPluginDescription.Permission.Default.OP;
        register("${permissionRoot}.cmd.option").get().default = BukkitPluginDescription.Permission.Default.OP;
        register("${permissionRoot}.cmd.reload").get().default = BukkitPluginDescription.Permission.Default.OP;

        register("${permissionRoot}.mobegg.use").get().default = BukkitPluginDescription.Permission.Default.TRUE;

        register("${permissionRoot}.bonemeal.flower").get().default = BukkitPluginDescription.Permission.Default.TRUE;
        register("${permissionRoot}.bonemeal.sugarcane").get().default = BukkitPluginDescription.Permission.Default.TRUE;
        register("${permissionRoot}.bonemeal.coral").get().default = BukkitPluginDescription.Permission.Default.TRUE;

        register("${permissionRoot}.shulkerbox.use").get().default = BukkitPluginDescription.Permission.Default.TRUE;
    }
}

// https://stackoverflow.com/a/74848372
tasks.withType<Jar> {
    exclude("plugin.yml")
}

// See https://github.com/jpenilla/run-task/wiki/Debugging#hot-swap
tasks.withType(xyz.jpenilla.runtask.task.AbstractRun::class) {
    javaLauncher = javaToolchains.launcherFor {
        vendor = JvmVendorSpec.JETBRAINS
        languageVersion = JavaLanguageVersion.of(21)
    }

    jvmArgs("-XX:+AllowEnhancedClassRedefinition", "-Dbstats.relocatecheck=false")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

tasks.shadowJar {

    if (System.getenv("NO_RELOCATE") == "yes") {
        System.out.println("Not relocating classes!")
    } else {
        minimize()
        relocate("xiamomc.pluginbase", "xyz.nifeather.fexp.shaded.pluginbase")
        relocate("org.bstats", "xyz.nifeather.fexp.shaded.bstats")
    }

}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
