# FeatherExperience plugin options
root:

  # The message pattern used for this plugin to display messages for players
  message_pattern: '[FExp] <message>'

  # Language
  language: en_us

  # Disable multi-language support?
  single_language: false

  # Features options
  features:
    # Bone meal options
    bone_meal:
      # Should we allow using bone meal on flowers?
      flower: true
      # Should we allow the usage of dispenser?
      flower_allow_dispenser: true

      # Enable renewable corals?
      coral: true
      # Should we allow the usage of dispenser?
      coral_allow_dispenser: true

      # Allow using bone meal on sugarcane?
      sugarcane: true
      # Should we allow the usage of dispenser?
      sugarcane_allow_dispenser: true

    # Deepslate options
    deepslate:
      # Enable deepslate farm?
      farm: true

    # Shulker box options
    shulkerbox:
      # Allow players open shulker box on their hand without placing it down?
      open: true

      # A workaround for some plugins that sync players' inventories across multiple servers.
      # Wait for the configured ticks before we allow someone to open a box after they join
      #
      # PS: 1 second = 20 ticks
      wkar_open_delay: 40

    # Save tridents from the void
    save_tridents_from_void:
      # Enable this feature?
      enabled: true

    # Can items with Fire Aspect light candles?
    # Note that due to some limitations, players should left-click them rather than right-click like on Bedrock
    fire_aspect_lit_candles: true

    # Should players not have XP cooldown?
    no_exp_cooldown: true

    # PvP options
    pvp:
      # Should we handle PvP events?
      enabled: true

      # The message to show when players enable their PvP
      enabled_message: "<color:#e0f2f1>PVP Enabled</color>"

      # The message to show when players disable their PvP
      disabled_message: "<color:#e0f2f1>PVP Disabled</color>"

    # Turn mobs into spawn eggs when clicked with an egg
    mob_eggs:
      # Enable this feature?
      enabled: true

      # Disable this feature in these worlds.
      # !!! Please note that players can still use the spawn egg in these worlds !!!
      #
      # Example:
      # disabled_worlds:
      #   - disabled_world1
      #   - disabled_world2
      disabled_worlds:
        - disabled_world1
        - disabled_world2

      # Disable this feature for certain mobs
      #
      # Example:
      # disabled_mobs:
      #   - minecraft:warden
      #   - minecraft:wither
      disabled_mobs:
        - minecraft:disabled_1
        - minecraft:disabled_2

      # Mob whitelist, only allow players to catch these mobs
      # Disabled when the list is empty
      #
      # Example:
      # mob_whitelist:
      #   - minecraft:villager
      #   - minecraft:allay
      mob_whitelist: []

    # Minecart speed settings
    # It will allow minecarts to run at different speed depend on which block it runs on
    minecart:
      # Enable this feature?
      enabled: true

      # Speed multipliers
      configs:
        - "minecraft:bedrock=1.5"

  # Do not touch unless you know what you're doing!
  version: 9
